export const actionTypes = {
  SET_ROOM: "SET_ROOM",
  SET_PLAYER_SYMBOL: "SET_PLAYER_SYMBOL",
  SET_PLAYER_TURN: "SET_PLAYER_TURN",
  SET_GAME: "SET_GAME",
  SET_BOARD: "SET_BOARD",
  REFRESH: "REFRESH",
  TRY_AGAIN: "TRY_AGAIN",
  SET_CLASSNAME: "SET_CLASSNAME",
};
