[[redirects]]
  from = "/register"
  to = "/login"
  status = 301
  

## This rule redirects to an external API, signing requests with a secret
[[redirects]]
  from = "/login"
  to = "/"
  status = 200
